# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 827296c2a34e9d2406a119810c94ac9e35fd3853bd1743b4874a50473028620518ea303cad4836507deb7b3ec0068089c439e9410b994d1f5ce0e304f3bd7252

test:
  secret_key_base: a09a93bb58e6d2777cd8b96626664e706bd75b785e53afeb57fe9bf2e06340c302257e7404b19927abbd8612b28e06d83f70dd2e48585daac264ed6272d11ae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
